blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/smitt14ua/zeus/discussions
    about: Ask questions or discuss ideas before opening a formal issue
