name: Test

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go test ./... -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          fail_ci_if_error: true
